resdex/.gitignore, resdex/package-lock.json, resdex/package.json, resdex/src/App.js, resdex/src/firebaseConfig.js, resdex/src/index.css, resdex/src/pages/Login.js, resdex/src/pages/Success.js, resdex/src/pages/privateroute.js, resdex/src/pages/signup.js
=> Firebase Auth Implementation

resdex/src/index.css, resdex/src/pages/PDFUpload.js, resdex/src/pages/Profile.js
--> pdf viewing external redirect
--> AWS S3 Bucket (CORS Update) for non-auth users during Fetch process
--> pdf field attributes for pdfurl.title and pdfurl.desc from firebase db
=> pdf component

resdex/src/pages/About.js, resdex/src/pages/Home.js, resdex/src/pages/Login.js, resdex/src/pages/Navbar.js, resdex/src/pages/Profile.js, resdex/src/pages/signup.js
--> Confirm password
--> Sign up and instantly logged in w/o verification fix. -->Logout on confirm since @Fshah05 kept clicking by accident :laughing:
=> Fix Issues #14

resdex/package-lock.json, resdex/package.json, resdex/src/pages/PDFUpload.js, resdex/src/pages/signup.js
--> Made sure username follows specific regex on signup. (disabled the use of special characters for link clarity)
--> Changed PDF S3 Bucket handling. Set a predefined rate-limit of 10 uploads a day along with a max of 5MB each. May need to implement compression strategies later on for larger files. (Will help against unwanted malicious activity towards database and keep well within upload tier).
=> username regex + pdf handling

resdex/src/App.js, resdex/src/index.css, resdex/src/pages/Navbar.js, resdex/src/pages/Search.js
Added search functionality for users.
--> Used Firebase queries
--> For now limited to 10 listings (to avoid excessive reads. --> Changed Navbar text to icons for now (May revert back later) --> Currently user's indexing, need to create an index for projects.
=> Major Update

resdex/src/App.js, resdex/src/pages/Contact.js, resdex/src/pages/Success.js
--> Navigates to success page on ticket submission.
=> added success page redirect

resdex/src/App.js, resdex/src/Releases/V101.js, resdex/src/pages/About.js, resdex/src/pages/Profile.js, resdex/src/pages/Team.js
--> will help for tag and field changes
=> changed edit section to modal

resdex/package-lock.json, resdex/package.json, resdex/src/pages/PDFUpload.js, resdex/src/pages/Profile.js
changed layout for uploading documents
changed research display from inline flat to carousel controlled. (Double check for cache uploading to avoid fetch during carousel automatic toggling)
=> changed framework

resdex/src/App.js, resdex/src/pages/Contact.js, resdex/src/pages/Footer.js
footer to top onClick
contact page resizing (margins)
=> minor changes

resdex/src/pages/PDFUpload.js, resdex/src/pages/Profile.js
--> tags when uploading documents
=> added tags for documents

resdex/src/index.css, resdex/src/pages/Profile.js
moved upload container component to main profile card.
(had exclusion beforehand due to component difference visually)
=> framework update

resdex/src/pages/ReleaseDocs.js, resdex/src/pages/ReleaseInfo.js
=> Added Patch Notes

resdex/src/pages/ReleaseDocs.js, resdex/src/pages/ReleaseInfo.js
=> Updated Release Notes

resdex/src/pages/Profile.js
Profile attributes (organization, about me, interests) can only be updated one by one. Fix to allow for all simultaneously being edited.
task completed
attributes can now be saved all at once also removed all at once.
=> Profile Attributes only saving one by one

resdex/src/pages/Home.js
=> removed line

resdex/src/index.css, resdex/src/pages/Home.js
- added "mission statement"
- added "values" section
- moved scroller bar between "mission statement" and values
**NEGLECT IN PATCH NOTES**
=> Updated Home Page

resdex/package-lock.json, resdex/package.json, resdex/src/index.css, resdex/src/pages/Home.js, resdex/src/pages/Navbar.js
- added tooltips for each navbar icon (Home, Login, Search, etc.)
- works for when you're logged in and logged out
=> Navbar Icons (Tooltip)

resdex/package-lock.json, resdex/package.json, resdex/src/pages/Home.js, resdex/src/pages/Profile.js
- Added conditional visibility for "Share Profile" button (Meaning only the person logged in can see share profile)
- Added a dedicated modal page with clean layout for sharing options (Will implement QR Code in future update)
- Added pop-up toast which says "Profile link copied to clipboard" for UI readability whenever the profile link is copied
=> Share Profile Modal Update

resdex/src/pages/PDFUpload.js, resdex/src/pages/Profile.js
- Added a modal for upload options in PDFUpload, allowing users to choose between creating a document or importing one.
=> Enhance PDFUpload and Profile components

resdex/REFACTORING_SUMMARY.md, resdex/src/components/common/FormField.js, resdex/src/components/common/LoadingSpinner.js, resdex/src/components/common/Logo.js, resdex/src/components/common/MessageDisplay.js, resdex/src/components/common/PageHeader.js, resdex/src/components/common/index.js, resdex/src/hooks/useAnimationEffect.js, resdex/src/pages/About.js, resdex/src/pages/Contact.js, resdex/src/pages/Home.js, resdex/src/pages/Login.js, resdex/src/pages/Notifications.js, resdex/src/pages/Search.js, resdex/src/pages/Team.js, resdex/src/pages/signup.js
- Introduced a detailed refactoring summary document outlining improvements in modularity, code reduction, and adherence to React best practices.
- Created new reusable components: `FormField`, `Logo`, `MessageDisplay`, `LoadingSpinner`, and `PageHeader` to standardize UI elements and enhance maintainability.
- Implemented a custom hook `useAnimationEffect` for handling animations across multiple components.
- Refactored existing components (Login, Signup, Contact, etc.) to utilize new components and hooks, significantly reducing code duplication and improving readability.
=> Add comprehensive refactoring summary and new reusable components

resdex/src/pages/Search.js
- Added support for searching universities, including a dropdown for university suggestions based on user input.
- Integrated `canadianUniversities` data to filter suggestions when the search type is set to "universities".
- Enhanced the search input to clear previous results and suggestions when the search type changes.
- Implemented a click handler for university suggestions to populate the search input and trigger a search.
- Updated UI styles for better responsiveness based on the selected search type.
=> Implement university search functionality in Search component

resdex/src/pages/Notifications.js
- Introduced a new function to check for accepted follow notifications.
- Updated the authentication state handling to set the current user more effectively.
- Refactored the notification fetching logic to use the current user ID.
- Enhanced the handling of accepting and declining follow requests, including updating user notifications and maintaining state.
- Improved the UI for displaying notifications, including a clearer structure for pending requests and accepted notifications.
- Added functionality to dismiss notifications and reload the page for real-time updates.
=> Refactor Notifications component for improved notification handling

resdex/package-lock.json, resdex/package.json, resdex/src/pages/Profile.js
- Integrated `qrcode.react` library to generate a QR code for sharing the profile link.
- Updated the Profile component to include a QR code section in the share modal.
- Enhanced the UI for share buttons and added hover effects for better user interaction.
- Removed redundant share button and improved layout for a cleaner design.
=> Add QR code sharing functionality to Profile page

resdex/src/pages/Notifications.js, resdex/src/pages/Profile.js, resdex/src/pages/Team.js
- Added a new function to format timestamps without seconds for better readability.
- Updated the notification display to use the new timestamp formatting function.
=> Enhance Notifications component with timestamp formatting

resdex/package-lock.json, resdex/package.json, resdex/src/pages/Profile.js, resdex/src/pages/ProfilePictureUpload.js, resdex/src/pages/Search.js
- Ctrl + Click on a user's "View profile" takes you to a separate tab
- Added custom crop for profile picture upload
=> Profile Updates

resdex/src/pages/Profile.js, resdex/src/pages/Team.js
- Added Darsh Kansara to team page
- Added transition fade out for "profile link copied"
=> Updated Team and Profile Page

resdex/src/pages/ChatBox.js, resdex/src/pages/Profile.js, resdex/src/pages/Search.js
Made chatbox ui cleaner, text, background and background matches the websites aesthetics (almost)
=> Chatbox UI

resdex/src/index.css, resdex/src/pages/Profile.js, resdex/src/pages/ProfilePictureUpload.js, resdex/src/pages/Search.js
- added verification badge to members who are on the ResDex Team
- tooltip also included for hover "Team Member"
=> Added Verification Badge

resdex/src/pages/Create.js, resdex/src/pages/Search.js
- Improved the user experience by disabling options without linked Gmail accounts in the collaborators select component.
=> Added Gmail account linking status to collaborator options in Create.js.

resdex/src/pages/Profile.js
- fixed preview for certifications
- fixed preview for researched documents
=> Previews Update

resdex/server/.gitignore, resdex/server/package-lock.json, resdex/server/package.json, resdex/server/server.js, resdex/src/App.js, resdex/src/components/ChatWindow.js, resdex/src/hooks/useChats.js, resdex/src/pages/Messages.css, resdex/src/pages/Messages.js, resdex/src/pages/Navbar.js
=> messages page - jay

resdex/src/index.css
the dots for testimonial are smaller now, not stretched out
=> Update index.css 

resdex-v2/src/app/digest/[id]/Article.tsx
--> right sidebar will now show below summary as horizontal scrolling
--> left sidebar simplified
=> updated digest specific view

resdex-v2/src/app/messages/page.tsx, resdex-v2/src/app/profile/[username]/page.tsx, resdex-v2/src/components/ui/SearchBar.tsx, resdex-v2/src/components/ui/navbar.tsx
merging for recent changes so branch can be up to date for #140
=> Feed system
